title: Dominik Cvetkovski # your name (or website title) here
logo: "/images/ProfileImage.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date of bith: 14.04.1998.
  Age: 23
  Location: Zagreb / Novska, Croatia

  <br><br>
  <b> Programming skills: </b>
  <br>
  - Unity C# ⭐⭐⭐⭐⭐
  <br>
  - Unreal Engine C++ ⭐⭐⭐⭐⭐
  <br>
  - Python ⭐⭐
  <br>
  - HTML5 ⭐
  <br>
  
  Software
  - Photoshop ⭐⭐⭐⭐⭐
  - Ilustrator ⭐⭐⭐⭐
  - MakeHuman ⭐⭐⭐⭐⭐
  - Fuse ⭐⭐⭐⭐
  - Mixamo ⭐⭐⭐⭐⭐
  
  <br><br>
  <a href="https://www.linkedin.com/in/dominik-cvetkovski-602566143/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
